- name: "Passito 3 (белый)"
  category: "podes"
  price: 3800
  description: "Описание товара"
  image: "/images/passito-3.png"
- name: "злая монашка"
  category: "liquids"
  price: 500
  description: "Описание товара"
  image: "/images/monashka.jpg"
- name: "подонки"
  category: "liquids"
  price: 500
  description: "Описание товара"
  image: "/images/podonki.jpg